window.APP_COPY = {
    de: {
        navigationDesktop: ['Ueber mich', 'My skills', 'Portfolio'],
        navigationMobile: ['Ueber mich', 'My skills', 'Portfolio', 'Kontakt'],
        verticalHeadline: 'Ich bin',
        jobTitle: 'FRONTEND ENTWICKLER',
        scrollHtml: 'Nach unten scrollen<p class="arrow">&#x279C;</p>',
        sectionTitle: 'Ueber mich',
        aboutText: 'Ich bin leidenschaftlicher Frontend-Entwickler und entwickle moderne, benutzerfreundliche Webanwendungen. Meine Motivation ist es, Technik in klare und intuitive Erlebnisse zu verwandeln und mich dabei staendig weiterzuentwickeln.',
        locationText: 'Ich arbeite in Deutschland und bin offen fuer Remote-Arbeit sowie neue Standorte, wenn das Projekt und das Team passen.',
        openMindedText: 'Ich bin neugierig auf neue Technologien, lerne schnell und verbessere meine Faehigkeiten kontinuierlich.',
        puzzleText: 'Ich loese Probleme strukturiert und kreativ. Komplexe Aufgaben zerlege ich in klare Schritte und finde effiziente, nachhaltige Loesungen.',
        skillsTitle: 'Meine Skills',
        skillsDescription: 'Ich habe in meinen Projekten verschiedene Frontend-Technologien eingesetzt und praxisnah kombiniert.',
        skillsQuestionHtml: 'Suchst du <span>eine weitere Skill</span>?',
        skillsSubtext: 'Ich lerne gerne neue Technologien und Frameworks, um mich stetig weiterzuentwickeln.',
        portfolioSubtitle: 'Hier findest du eine Auswahl meiner Projekte und einen Einblick in meine praktischen Faehigkeiten.',
        portfolioDescriptions: [
            'Task-Manager nach dem Kanban-Prinzip. Aufgaben koennen per Drag and Drop organisiert und verschiedenen Personen sowie Kategorien zugeordnet werden.',
            'Eine Bestell-App, mit der Nutzer Menues durchsuchen, Produkte in den Warenkorb legen und Bestellungen absenden koennen.',
            'Eine Foto-Sharing-App zum Hochladen, Teilen und Entdecken von Bildern mit moderner Benutzeroberflaeche.',
            'Eine Rezept-App mit klarer Struktur und benutzerfreundlicher Navigation fuer schnelles Finden von Inhalten.',
            'Ein Pokedex-Projekt mit Fokus auf API-Integration, Datenaufbereitung und uebersichtliche Darstellung.',
            'Ein 2D-Jump-and-Run-Spiel mit objektorientierter Struktur, Animationen und interaktiver Spielmechanik'
        ],
        contactTitle: 'Kontakt',
        contactProblem: 'Hast du ein Problem zu loesen?',
        contactText: 'Ich bin offen fuer neue Projekte und spannende Herausforderungen. Schreib mir gerne, dann schauen wir gemeinsam auf eine passende Loesung.',
        placeholderName: 'Dein Name',
        placeholderEmail: 'Deine E-Mail',
        placeholderMessage: 'Deine Nachricht',
        contactPolicyHtml: 'Ich habe die <a href="legal-notice.html#datenschutz" class="privacy-link">Datenschutzerklaerung</a> gelesen und stimme der Verarbeitung meiner Daten zu.',
        emptyReviewText: 'Noch keine Kommentare. Hinterlasse ueber den Button dein Feedback.',
        emptyReviewName: 'Dein Kommentar erscheint hier',
        emptyReviewAlt: 'Platzhalter fuer Kommentare',
    },
    en: {
        navigationDesktop: ['About me', 'My skills', 'Portfolio'],
        navigationMobile: ['About me', 'My skills', 'Portfolio', 'Contact'],
        verticalHeadline: 'I am',
        jobTitle: 'FRONTEND DEVELOPER',
        scrollHtml: 'Scroll down<p class="arrow">&#x279C;</p>',
        sectionTitle: 'About me',
        aboutText: 'Write some information about yourself that is IT related. Why are you passionate about coding? What is your source of inspiration for improving your programming skills?',
        locationText: 'Where are you located? Are you open to different ways of working, such as working remotely or even relocating?',
        openMindedText: 'Show that you are open-minded. Are you enthusiastic about learning new technologies and continually improving your skills?',
        puzzleText: 'A brief description of your problem-solving approach. Do you learn from each challenge as you search for the most efficient or elegant solution? You can include some keywords like: analytical thinking, creativity, persistence and collaboration.',
        skillsTitle: 'My skills',
        skillsDescription: 'Show that you have used a variety of front-end technologies in your projects.',
        skillsQuestionHtml: 'Looking for <span>another skill</span>?',
        skillsSubtext: 'Reveal enthusiasm for learning new technologies and frameworks.',
        portfolioSubtitle: 'Explore a selection of my work here - Interact with projects to see my skills in action.',
        portfolioDescriptions: [
            'Task manager inspired by the Kanban System. Let you and your team organize tasks using drag and drop functionality, assign tasks to different users and categories.',
            'A food ordering app that allows users to browse a menu, add items to their cart, and place orders. The app features a user-friendly interface, real-time order tracking, and secure payment processing.',
            'A photo sharing app that allows users to upload, share, and discover photos. The app features a user-friendly interface, real-time photo updates, and secure authentication.',
            'A recipe app that allows users to browse a menu, add items to their cart, and place orders. The app features a user-friendly interface, real-time order tracking, and secure payment processing.',
            'A pokedex app that allows users to browse a menu, add items to their cart, and place orders. The app features a user-friendly interface, real-time order tracking, and secure payment processing.',
            'A food ordering app that allows users to browse a menu, add items to their cart, and place orders. The app features a user-friendly interface, real-time order tracking, and secure payment processing.'
        ],
        contactTitle: 'Contact',
        contactProblem: 'Got a problem to solve?',
        contactText: 'I am always open to new challenges and opportunities. If you have a project in mind or just want to say hi, feel free to reach out. Let\'s connect and see how we can work together!',
        placeholderName: 'Your name',
        placeholderEmail: 'Your email',
        placeholderMessage: 'Your message',
        contactPolicyHtml: 'I\'ve read the <a href="legal-notice.html#datenschutz" class="privacy-link">privacy policy</a> and agree to the processing of my data as outlined.',
        emptyReviewText: 'No comments yet. Leave your feedback using the button below.',
        emptyReviewName: 'Your comment will appear here',
        emptyReviewAlt: 'Placeholder for comments',
    }
};
