window.APP_COPY = {
    de: {
        navigationDesktop: ['Über mich', 'Meine Skills', 'Portfolio'],
        navigationMobile: ['Über mich', 'Meine Skills', 'Portfolio', 'Kontakt'],
        verticalHeadline: 'Ich bin',
        jobTitle: 'FRONTEND ENTWICKLER',
        scrollHtml: 'Nach unten scrollen<p class="arrow">&#x279C;</p>',
        sectionTitle: 'Über mich',
        aboutText: 'Ich bin leidenschaftlicher Frontend-Entwickler und entwickle moderne, benutzerfreundliche Webanwendungen. Meine Motivation ist es, Technik in klare und intuitive Erlebnisse zu verwandeln und mich dabei ständig weiterzuentwickeln.',
        locationText: 'Ich arbeite in Deutschland und bin offen für Remote-Arbeit sowie neue Standorte, wenn das Projekt und das Team passen.',
        openMindedText: 'Ich bin neugierig auf neue Technologien, lerne schnell und verbessere meine Fähigkeiten kontinuierlich.',
        puzzleText: 'Ich löse Probleme strukturiert und kreativ. Komplexe Aufgaben zerlege ich in klare Schritte und finde effiziente, nachhaltige Lösungen.',
        skillsTitle: 'Meine Skills',
        skillsDescription: 'Ich habe in meinen Projekten verschiedene Frontend-Technologien eingesetzt und praxisnah kombiniert.',
        skillsQuestionHtml: 'Suchst du <span>eine weitere Skill</span>?',
        skillsSubtext: 'Ich lerne gerne neue Technologien und Frameworks, um mich stetig weiterzuentwickeln.',
        portfolioSubtitle: 'Hier findest du eine Auswahl meiner Projekte und einen Einblick in meine praktischen Fähigkeiten.',
        portfolioDescriptions: [
            'Task-Manager nach dem Kanban-Prinzip. Aufgaben können per Drag and Drop organisiert und verschiedenen Personen sowie Kategorien zugeordnet werden.',
            'Eine Bestell-App, mit der Nutzer Menüs durchsuchen, Produkte in den Warenkorb legen und Bestellungen absenden können.',
            'Eine Foto-Sharing-App zum Hochladen, Teilen und Entdecken von Bildern mit moderner Benutzeroberfläche.',
            'Eine Rezept-App mit klarer Struktur und benutzerfreundlicher Navigation für schnelles Finden von Inhalten.',
            'Ein Pokedex-Projekt mit Fokus auf API-Integration, Datenaufbereitung und übersichtliche Darstellung.',
            'Ein 2D-Jump-and-Run-Spiel mit objektorientierter Struktur, Animationen und interaktiver Spielmechanik'
        ],
        contactTitle: 'Kontakt',
        contactProblem: 'Hast du ein Problem zu lösen?',
        contactText: 'Ich bin offen für neue Projekte und spannende Herausforderungen. Schreib mir gerne, dann schauen wir gemeinsam auf eine passende Lösung.',
        placeholderName: 'Dein Name',
        placeholderEmail: 'Deine E-Mail',
        placeholderMessage: 'Deine Nachricht',
        contactPolicyHtml: 'Ich habe die <a href="legal-notice.html#datenschutz" class="privacy-link">Datenschutzerklärung</a> gelesen und stimme der Verarbeitung meiner Daten zu.',
        contactSubmitButtonText: 'Nachricht senden :)',
        getInTouchButtonText: 'Kontakt aufnehmen',
        letsTalkButtonText: 'Lass uns reden!',
        reviewCommentButtonText: 'Kommentar hinterlassen',
        reviewCommentDialogTitle: 'Kommentar hinterlassen',
        emptyReviewText: 'Noch keine Kommentare. Hinterlasse über den Button dein Feedback.',
        emptyReviewName: 'Dein Kommentar erscheint hier',
        emptyReviewAlt: 'Platzhalter für Kommentare',
        reviewSubmittedNotification: 'Kommentar wird bald veröffentlicht',
    },
    en: {
        navigationDesktop: ['About me', 'My skills', 'Portfolio'],
        navigationMobile: ['About me', 'My skills', 'Portfolio', 'Contact'],
        verticalHeadline: 'I am',
        jobTitle: 'FRONTEND DEVELOPER',
        scrollHtml: 'Scroll down<p class="arrow">&#x279C;</p>',
        sectionTitle: 'About me',
        aboutText: 'I am a passionate frontend developer who builds modern, user-friendly web applications. My motivation is to turn technology into clear, intuitive experiences while continuously growing my skills.',
        locationText: 'I am based in Germany and open to remote work as well as new locations when the project and team are the right fit.',
        openMindedText: 'I am curious about new technologies, learn quickly, and keep improving my skills over time.',
        puzzleText: 'I solve problems in a structured and creative way. I break complex tasks into clear steps and focus on efficient, sustainable solutions.',
        skillsTitle: 'My skills',
        skillsDescription: 'Show that you have used a variety of front-end technologies in your projects.',
        skillsQuestionHtml: 'Looking for <span>another skill</span>?',
        skillsSubtext: 'Reveal enthusiasm for learning new technologies and frameworks.',
        portfolioSubtitle: 'Explore a selection of my work here - Interact with projects to see my skills in action.',
        portfolioDescriptions: [
            'Task manager inspired by the Kanban System. Let you and your team organize tasks using drag and drop functionality, assign tasks to different users and categories.',
            'A food ordering app that allows users to browse a menu, add items to their cart, and place orders. The app features a user-friendly interface, real-time order tracking, and secure payment processing.',
            'A photo sharing app that allows users to upload, share, and discover photos. The app features a user-friendly interface, real-time photo updates, and secure authentication.',
            'A recipe app that allows users to browse a menu, add items to their cart, and place orders. The app features a user-friendly interface, real-time order tracking, and secure payment processing.',
            'A pokedex app that allows users to browse a menu, add items to their cart, and place orders. The app features a user-friendly interface, real-time order tracking, and secure payment processing.',
            'A food ordering app that allows users to browse a menu, add items to their cart, and place orders. The app features a user-friendly interface, real-time order tracking, and secure payment processing.'
        ],
        contactTitle: 'Contact',
        contactProblem: 'Got a problem to solve?',
        contactText: 'I am always open to new challenges and opportunities. If you have a project in mind or just want to say hi, feel free to reach out. Let\'s connect and see how we can work together!',
        placeholderName: 'Your name',
        placeholderEmail: 'Your email',
        placeholderMessage: 'Your message',
        contactPolicyHtml: 'I\'ve read the <a href="legal-notice.html#datenschutz" class="privacy-link">privacy policy</a> and agree to the processing of my data as outlined.',
        contactSubmitButtonText: 'Send message :)',
        getInTouchButtonText: 'Get in touch',
        letsTalkButtonText: 'Let\'s talk!',
        reviewCommentButtonText: 'Leave a comment',
        reviewCommentDialogTitle: 'Leave a Comment',
        emptyReviewText: 'No comments yet. Leave your feedback using the button below.',
        emptyReviewName: 'Your comment will appear here',
        emptyReviewAlt: 'Placeholder for comments',
        reviewSubmittedNotification: 'Your comment will be published soon',
    }
};
